trigger:
  branches:
    include:
      - Automation

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.0.100-rc.2.25502.107'

- script: dotnet tool restore
  displayName: 'Restore dotnet tools'

- script: |
    cd All/Automation
    dotnet tool restore
    dotnet tool run playwright install --with-deps
  displayName: 'Install Playwright Browsers'

- script: |
    cd All  
    dotnet restore
  displayName: 'Dotnet restore'

- script: dotnet build All.sln --configuration Release
  displayName: 'Build'

- script: dotnet test All/Automation/Automation.csproj --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx" --results-directory $(Build.ArtifactStagingDirectory)/test-results
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/test-results/*.trx'
    failTaskOnFailedTests: true
